name: OIDC AWS Config

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  configure-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::084828598848:role/oidc-checker-hadi
          aws-region: us-east-1
